name: Build BarberSalon

on:
  push:

jobs:
  build:
    runs-on: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check .NET
        run: dotnet --info
      
      - name: Show working directory
        run: |
          Write-Host "PWD: $PWD"
          Write-Host "WORKSPACE: $env:GITHUB_WORKSPACE"

      - name: Debug - dump environment
        run: | 
          Get-ChildItem Env: | Sort-Object Name
      
      - name: Restore
        run: dotnet restore src/BarberSalon.API/BarberSalon.API.csproj -bl:C:\temp\restore.binlog

      - name: Build
        run: dotnet build src/BarberSalon.API/BarberSalon.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/BarberSalon.API/BarberSalon.API.csproj --configuration Release --output "$env:GITHUB_WORKSPACE\publish" --no-restore

      - name: Show published files
        run: Get-ChildItem "$env:GITHUB_WORKSPACE\publish" -Recurse