name: Build BarberSalon

on:
  push:

jobs:
  build:
    runs-on: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find .NET projects
        run: Get-ChildItem -Path . -Filter *.csproj -Recurse | Select-Object FullName

      - name: Check .NET
        run: dotnet --info
        
      #- name: restore
       # run: dotenet restore Barbersalon.slnx

      #- name: build
       #  run: dotnet build BarberSalon.slnx --configuration Release --no-restore
